name: Cyber Scraper Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Start Cyber Scraper
      run: streamlit run main.py &
    
    - name: Start ngrok to expose Streamlit port 8501
      run: ngrok http 8501
      continue-on-error: true

    - name: Display ngrok Public URL
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq ".tunnels[0].public_url"
